version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
      # - "5432:5432"

  api:
    build:
      context: .
      dockerfile: dockerfile.api
    environment:
      - DB_CONN_STR=postgresql://postgres:postgres@db/postgres
    depends_on:
      - db
      

  storage:
    build:
      context: storagemock
      dockerfile: dockerfile
    environment:
      - API_URL=http://api

  nginx:
    image: nginx:1.21
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
      - oauth
    
  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend

  oauth:
    build:
      context: oauthmock
      dockerfile: dockerfile
    ports:
      - "8080:8080"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "5001:8080"
    environment:
      - URL=https://raw.githubusercontent.com/AirWalk-Digital/airview-api/main/docs/openapi.json
      
