version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: dockerfile.api
    environment:
      - DB_CONN_STR=postgresql://postgres:postgres@db/postgres
    depends_on:
      - db
      
  cms-api:
    build:
      context: cms-api
    environment:
      - GITHUB_REPO_NAME
      - GITHUB_ORG_NAME
      - GITHUB_INSTALLATION_ID
      - GITHUB_APP_ID
      - GITHUB_PRIVATE_KEY_FILE
    volumes:
      - ./github-app-private-key.pem:/private-key.pem
    depends_on:
      - db

      
  exclusion_engine:
    build:
      context: exclusionmock 
      dockerfile: dockerfile
    depends_on:
      - api
    

  nginx:
    image: nginx:1.21
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - cms-api

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "5001:8080"
    environment:
      - URL=https://raw.githubusercontent.com/AirWalk-Digital/airview-api/main/docs/openapi.json
      
