[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"

[api]
  dashboard = true

[certificatesResolvers.lets-encrypt.acme]
  email = "your_email@noreply.com"
  storage = "shared/acme.json"
  [certificatesResolvers.lets-encrypt.acme.tlsChallenge]

  filename = "traefik_dynamic.toml"